name: Sync from upstream

on:
  schedule:
    - cron: "0 3 * * *"   # jeden Tag um 03:00 UTC
  workflow_dispatch:      # auch manuell startbar

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/Feuerwehrverein-Raura/Homepage.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories || true

      - name: Push changes
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
